// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbk5MlcZj9XSMXB2xTdV_o5acw_nnapQI',
    appId: '1:1060644680160:web:ce6629649eaa4aa1db7b85',
    messagingSenderId: '1060644680160',
    projectId: 'marg-rakshak-8faf4',
    authDomain: 'marg-rakshak-8faf4.firebaseapp.com',
    storageBucket: 'marg-rakshak-8faf4.appspot.com',
    measurementId: 'G-YFH5TWXXMM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuOZQjw3NgSaEan6Tlig7E8b9TwKpFFtg',
    appId: '1:1060644680160:android:9c79d3eb8c24cf5fdb7b85',
    messagingSenderId: '1060644680160',
    projectId: 'marg-rakshak-8faf4',
    storageBucket: 'marg-rakshak-8faf4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA-xuqkA9Qj6FqPuKtd2ENrdunIwjXD68',
    appId: '1:1060644680160:ios:2fe20803ce4eb024db7b85',
    messagingSenderId: '1060644680160',
    projectId: 'marg-rakshak-8faf4',
    storageBucket: 'marg-rakshak-8faf4.appspot.com',
    androidClientId: '1060644680160-5ajn4i3areen4alpcfelu2do6gk4q4o3.apps.googleusercontent.com',
    iosClientId: '1060644680160-2domigrckhulngi9j30l1mb1kntlrktc.apps.googleusercontent.com',
    iosBundleId: 'com.example.margRakshak',
  );
}
